// 성경 목차 맵
export const BIBLE_BOOKS = {
  // 구약 (Old Testament)
  "창세기": {
    korean: "창세기",
    english: "Genesis",
    testament: "OT",
    categoryNumber: 136929,
  },
  "출애굽기": {
    korean: "출애굽기",
    english: "Exodus",
    testament: "OT",
    categoryNumber: 136930,
  },
  "레위기": {
    korean: "레위기",
    english: "Leviticus",
    testament: "OT",
    categoryNumber: 136931,
  },
  "민수기": {
    korean: "민수기",
    english: "Numbers",
    testament: "OT",
    categoryNumber: 136932,
  },
  "신명기": {
    korean: "신명기",
    english: "Deuteronomy",
    testament: "OT",
    categoryNumber: 136933,
  },
  "여호수아": {
    korean: "여호수아",
    english: "Joshua",
    testament: "OT",
    categoryNumber: 136934,
  },
  "사사기": {
    korean: "사사기",
    english: "Judges",
    testament: "OT",
    categoryNumber: 136935,
  },
  "룻기": {
    korean: "룻기",
    english: "Ruth",
    testament: "OT",
    categoryNumber: 136936,
  },
  "사무엘상": {
    korean: "사무엘상",
    english: "1Samuel",
    testament: "OT",
    categoryNumber: 136937,
  },
  "사무엘하": {
    korean: "사무엘하",
    english: "2Samuel",
    testament: "OT",
    categoryNumber: 136938,
  },
  "열왕기상": {
    korean: "열왕기상",
    english: "1Kings",
    testament: "OT",
    categoryNumber: 136939,
  },
  "열왕기하": {
    korean: "열왕기하",
    english: "2Kings",
    testament: "OT",
    categoryNumber: 136940,
  },
  "역대상": {
    korean: "역대상",
    english: "1Chronicles",
    testament: "OT",
    categoryNumber: 136941,
  },
  "역대하": {
    korean: "역대하",
    english: "2Chronicles",
    testament: "OT",
    categoryNumber: 136942,
  },
  "에스라": {
    korean: "에스라",
    english: "Ezra",
    testament: "OT",
    categoryNumber: 136943,
  },
  "느헤미야": {
    korean: "느헤미야",
    english: "Nehemiah",
    testament: "OT",
    categoryNumber: 136944,
  },
  "에스더": {
    korean: "에스더",
    english: "Esther",
    testament: "OT",
    categoryNumber: 136945,
  },
  "욥기": {
    korean: "욥기",
    english: "Job",
    testament: "OT",
    categoryNumber: 136946,
  },
  "시편": {
    korean: "시편",
    english: "Psalms",
    testament: "OT",
    categoryNumber: 136947,
  },
  "잠언": {
    korean: "잠언",
    english: "Proverbs",
    testament: "OT",
    categoryNumber: 136948,
  },
  "전도서": {
    korean: "전도서",
    english: "Ecclesiastes",
    testament: "OT",
    categoryNumber: 136949,
  },
  "아가": {
    korean: "아가",
    english: "SongofSongs",
    testament: "OT",
    categoryNumber: 136950,
  },
  "이사야": {
    korean: "이사야",
    english: "Isaiah",
    testament: "OT",
    categoryNumber: 136951,
  },
  "예레미야": {
    korean: "예레미야",
    english: "Jeremiah",
    testament: "OT",
    categoryNumber: 136952,
  },
  "예레미야애가": {
    korean: "예레미야애가",
    english: "Lamentations",
    testament: "OT",
    categoryNumber: 136953,
  },
  "에스겔": {
    korean: "에스겔",
    english: "Ezekiel",
    testament: "OT",
    categoryNumber: 136954,
  },
  "다니엘": {
    korean: "다니엘",
    english: "Daniel",
    testament: "OT",
    categoryNumber: 136955,
  },
  "호세아": {
    korean: "호세아",
    english: "Hosea",
    testament: "OT",
    categoryNumber: 136956,
  },
  "요엘": {
    korean: "요엘",
    english: "Joel",
    testament: "OT",
    categoryNumber: 136957,
  },
  "아모스": {
    korean: "아모스",
    english: "Amos",
    testament: "OT",
    categoryNumber: 136958,
  },
  "오바댜": {
    korean: "오바댜",
    english: "Obadiah",
    testament: "OT",
    categoryNumber: 136959,
  },
  "요나": {
    korean: "요나",
    english: "Jonah",
    testament: "OT",
    categoryNumber: 136960,
  },
  "미가": {
    korean: "미가",
    english: "Micah",
    testament: "OT",
    categoryNumber: 136961,
  },
  "나훔": {
    korean: "나훔",
    english: "Nahum",
    testament: "OT",
    categoryNumber: 136962,
  },
  "하박국": {
    korean: "하박국",
    english: "Habakkuk",
    testament: "OT",
    categoryNumber: 136963,
  },
  "스바냐": {
    korean: "스바냐",
    english: "Zephaniah",
    testament: "OT",
    categoryNumber: 136964,
  },
  "학개": {
    korean: "학개",
    english: "Haggai",
    testament: "OT",
    categoryNumber: 136965,
  },
  "스가랴": {
    korean: "스가랴",
    english: "Zechariah",
    testament: "OT",
    categoryNumber: 136966,
  },
  "말라기": {
    korean: "말라기",
    english: "Malachi",
    testament: "OT",
    categoryNumber: 136967,
  },

  // 신약 (New Testament)
  "마태복음": {
    korean: "마태복음",
    english: "Matthew",
    testament: "NT",
    categoryNumber: 136969,
  },
  "마가복음": {
    korean: "마가복음",
    english: "Mark",
    testament: "NT",
    categoryNumber: 136970,
  },
  "누가복음": {
    korean: "누가복음",
    english: "Luke",
    testament: "NT",
    categoryNumber: 136971,
  },
  "요한복음": {
    korean: "요한복음",
    english: "John",
    testament: "NT",
    categoryNumber: 136972,
  },
  "사도행전": {
    korean: "사도행전",
    english: "Acts",
    testament: "NT",
    categoryNumber: 136973,
  },
  "로마서": {
    korean: "로마서",
    english: "Romans",
    testament: "NT",
    categoryNumber: 136974,
  },
  "고린도전서": {
    korean: "고린도전서",
    english: "1Corinthians",
    testament: "NT",
    categoryNumber: 136975,
  },
  "고린도후서": {
    korean: "고린도후서",
    english: "2Corinthians",
    testament: "NT",
    categoryNumber: 136976,
  },
  "갈라디아서": {
    korean: "갈라디아서",
    english: "Galatians",
    testament: "NT",
    categoryNumber: 136977,
  },
  "에베소서": {
    korean: "에베소서",
    english: "Ephesians",
    testament: "NT",
    categoryNumber: 136978,
  },
  "빌립보서": {
    korean: "빌립보서",
    english: "Philippians",
    testament: "NT",
    categoryNumber: 136979,
  },
  "골로새서": {
    korean: "골로새서",
    english: "Colossians",
    testament: "NT",
    categoryNumber: 136980,
  },
  "데살로니가전서": {
    korean: "데살로니가전서",
    english: "1Thessalonians",
    testament: "NT",
    categoryNumber: 136981,
  },
  "데살로니가후서": {
    korean: "데살로니가후서",
    english: "2Thessalonians",
    testament: "NT",
    categoryNumber: 136982,
  },
  "디모데전서": {
    korean: "디모데전서",
    english: "1Timothy",
    testament: "NT",
    categoryNumber: 136983,
  },
  "디모데후서": {
    korean: "디모데후서",
    english: "2Timothy",
    testament: "NT",
    categoryNumber: 136984,
  },
  "디도서": {
    korean: "디도서",
    english: "Titus",
    testament: "NT",
    categoryNumber: 136985,
  },
  "빌레몬서": {
    korean: "빌레몬서",
    english: "Philemon",
    testament: "NT",
    categoryNumber: 136986,
  },
  "히브리서": {
    korean: "히브리서",
    english: "Hebrews",
    testament: "NT",
    categoryNumber: 136987,
  },
  "야고보서": {
    korean: "야고보서",
    english: "James",
    testament: "NT",
    categoryNumber: 136988,
  },
  "베드로전서": {
    korean: "베드로전서",
    english: "1Peter",
    testament: "NT",
    categoryNumber: 136989,
  },
  "베드로후서": {
    korean: "베드로후서",
    english: "2Peter",
    testament: "NT",
    categoryNumber: 136990,
  },
  "요한일서": {
    korean: "요한일서",
    english: "1John",
    testament: "NT",
    categoryNumber: 136991,
  },
  "요한이서": {
    korean: "요한이서",
    english: "2John",
    testament: "NT",
    categoryNumber: 136992,
  },
  "요한삼서": {
    korean: "요한삼서",
    english: "3John",
    testament: "NT",
    categoryNumber: 136993,
  },
  "유다서": {
    korean: "유다서",
    english: "Jude",
    testament: "NT",
    categoryNumber: 136994,
  },
  "요한계시록": {
    korean: "요한계시록",
    english: "Revelation",
    testament: "NT",
    categoryNumber: 136995,
  },
};

// 사용 예시
// const book = BIBLE_BOOKS["마태복음"];
// console.log(book.korean);      // "마태복음"
// console.log(book.english);      // "Matthew"
// console.log(book.testament);    // "NT"
// console.log(book.categoryNumber); // null (크롤링으로 채워야 함)

